version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
    - VITE_API_URL=http://backend:4000
    depends_on:
      - backend
    

  admin:
    build: ./admin
    container_name: admin
    ports:
      - "5174:5174"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge